spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8858
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
        namespace: 9abe0e1d-a061-4aba-a632-1486d0a4ccf0
  application:
    name: dalian-twop-store
server:
  port: 8020